### PR TITLE
Implement seeking

### LINKED ISSUE #5: Implement Seek for BlockOn and AsyncSeek for Unblock
Hello,

During a [smolt issue discussion](https://github.com/stjepang/smol/issues/79#issuecomment-645485379) i raised the need to preserve `std::io::Seek` traits when moving from/out async.

While it is possible to seek through access to the inner `std::io::Seek` with `file.with_mut(|f| f.seek(pos)).await?` it would be more convenient to seek from outer directly : `file.seek(pos).await?`.

Would you consider implementing `Seek` for `BlockOn<T>` when `T: AsyncSeek` and `AsyncSeek` for `Unblock<T>`  when `T: std::io::Seek` please ?

Cheers !

### PR DESCRIPTION
**Pull request by ghost**
@ririsoft How's this?

Closes #5

### CODE REVIEW

**Comment by ririsoft** [comment]
It looks great, but I am too much a beginner in async Rust to review your pull request, sorry.

I will pull your changes during the week and see how it matches with a personal project of mine which uses `http-rs/tide`, trying to implement http range requests (and thus the need for `AsyncSeek`). I will report back here my testing.

All I can say is that I have just tried `blocking` for spawning processes within an async flow, piping stdout and stdin, and I am very impressed by the API. `smol` + `blocking` are a joy to use.

I come from Go and to me it looks like this is the moment where Rust is becoming "state of the art" async programming. Thanks to your work I believe Rust is going farther than what goroutines brings to developers.

Congratulation, thank you for your work and please do not limit your creativity !

**Comment by ghost** [comment]
Thank you for the kind words!

No need to read the code in detail, I just wanted to make sure this is indeed what you were looking for :) I will merge the PR and publish a new version now.

I feel I'm very very close to reaching the sweet spot in async Rust. The final step I'm currently working on is to split `smol` into three totally independent crates:

1. `blocking` - this part is already done.
2. `async-io` - will contain `Async` and `Timer`, and will spawn a reactor thread for you if you forget to call `smol::run()`.
3. `multitask` - types `Task`, `Queue`, and `Worker` for building executors.

When this is done, `smol` will be just a trivial wrapper around those three crates. In fact, I think we'll be writing async programs without even thinking about "runtimes" anymore, or asking ourselves "what runtime should I choose?" because you can just pick tiny libraries rather than using big runtimes.

I'm also excited about the idea of other people writing more libraries like `smol` or utilities like `#[smol_potato::main]`.

**Comment by ghost** [comment]
I published v0.4.6 with this PR!

**Comment by ririsoft** [comment]
> No need to read the code in detail, I just wanted to make sure this is indeed what you were looking for :) I will merge the PR and publish a new version now.

This is exactly what I was looking for :)

> `smol` will be just a trivial wrapper around those three crates. In fact, I think we'll be writing async programs without even thinking about "runtimes" anymore, or asking ourselves "what runtime should I choose?" because you can just pick tiny libraries rather than using big runtimes.

This is indeed great to have small utilities that do one thing and do it well, like `blocking`, this is the unix philosophy after all. But you are doing it right, IMHO, by presenting the whole thing into smol. For big applications or for beginners like me it really helps to have a single crate which present the big picture as a coherent ecosystem. 

> I published v0.4.6 with this PR!

I am pulling it right away, this is the only thing I miss to remove async-std from my dependency tree, thanks !

**Comment by ghost** [comment]
> But you are doing it right, IMHO, by presenting the whole thing into smol. For big applications or for beginners like me it really helps to have a single crate which present the big picture as a coherent ecosystem.

Thanks for the feedback, I'll definitely take that into consideration. Btw, if you have any code to share where you're using `smol` or `blocking`, I'd love to take a look in order to learn more about how you're using them and how I can make them better.

**Comment by zicklag** [comment]
> I come from Go and to me it looks like this is the moment where Rust is becoming "state of the art" async programming. Thanks to your work I believe Rust is going farther than what goroutines brings to developers.

I've been thinking the same thing. :smiley: I'm really excited about `smol` and all this cool supporting work such as `blocking` and `async_channel`. Keep up the good work!

**Pull request merged**
